# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-makelogs
  description: Buildkite Pipeline for makelogs
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/makelogs

spec:
  type: buildkite-pipeline
  owner: group:kibana-operations
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: makelogs
      description: 
    spec:
      repository: elastic/makelogs
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        kibana-operations:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
